#####################################################################
#                         SimpleDiscordLink                         #
#####################################################################

# For any help configuring this plugin, please go to the spigot page
# https://www.spigotmc.org/resources/simplediscordlink.95893/



vote-link: 'Change this text in the config.yml'